language: node_js
node_js:
  - "11"
install:
  - npm install
script:
  - npm run build
after_script:
  - cd ./dist
  - git init
  - git config user.name "qizhi"
  - git config user.email "qizhi03@meituan.com"
  - git add .
  - git commit -m "Update documents"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" "master:gh-pages"